//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input/MenuInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MenuInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MenuInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MenuInputActions"",
    ""maps"": [
        {
            ""name"": ""PopupMenu"",
            ""id"": ""52205f45-b032-49a4-aa02-748b51e014f6"",
            ""actions"": [
                {
                    ""name"": ""ToggleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""bd51f04a-025c-4a8d-93e2-63774dc44469"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""54d77910-939c-4c87-adc0-fd0703861432"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PopupMenu
        m_PopupMenu = asset.FindActionMap("PopupMenu", throwIfNotFound: true);
        m_PopupMenu_ToggleMenu = m_PopupMenu.FindAction("ToggleMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PopupMenu
    private readonly InputActionMap m_PopupMenu;
    private List<IPopupMenuActions> m_PopupMenuActionsCallbackInterfaces = new List<IPopupMenuActions>();
    private readonly InputAction m_PopupMenu_ToggleMenu;
    public struct PopupMenuActions
    {
        private @MenuInputActions m_Wrapper;
        public PopupMenuActions(@MenuInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleMenu => m_Wrapper.m_PopupMenu_ToggleMenu;
        public InputActionMap Get() { return m_Wrapper.m_PopupMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PopupMenuActions set) { return set.Get(); }
        public void AddCallbacks(IPopupMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_PopupMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PopupMenuActionsCallbackInterfaces.Add(instance);
            @ToggleMenu.started += instance.OnToggleMenu;
            @ToggleMenu.performed += instance.OnToggleMenu;
            @ToggleMenu.canceled += instance.OnToggleMenu;
        }

        private void UnregisterCallbacks(IPopupMenuActions instance)
        {
            @ToggleMenu.started -= instance.OnToggleMenu;
            @ToggleMenu.performed -= instance.OnToggleMenu;
            @ToggleMenu.canceled -= instance.OnToggleMenu;
        }

        public void RemoveCallbacks(IPopupMenuActions instance)
        {
            if (m_Wrapper.m_PopupMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPopupMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_PopupMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PopupMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PopupMenuActions @PopupMenu => new PopupMenuActions(this);
    public interface IPopupMenuActions
    {
        void OnToggleMenu(InputAction.CallbackContext context);
    }
}
